name = "webabc-next"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# Optional: If you use KV for caching
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "your-kv-namespace-id"